steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           |'us-central1-docker.pkg.dev/meetingapp-arkashree-408209/meetingapp/myimage:${SHORT_SHA}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/meetingapp-arkashree-408209/meetingapp/myimage:${SHORT_SHA}']

# Store images in Google Artifact Registry
images:
 - us-central1-docker.pkg.dev/meetingapp-arkashree-408209/meetingapp/myimage:${SHORT_SHA}

   # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'create-with-container', 'my-vm-name',
           '--container-image', 
           'us-central1-docker.pkg.dev/meetingapp-arkashree-408209/meetingapp/myimage:${SHORT_SHA}]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
